site_name: ALTERNATIVE Platform Documentation
site_url: https://platform.alternative-project.eu
repo_url: https://github.com/ALTERNATIVE-EU/alternative.github.io
repo_name: ALTERNATIVE-EU/alternative.github.io

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - toc.follow

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
  - abbr
  - toc:
      permalink: true

nav:
  - Overview: index.md
  - Architecture:
      - Introduction: architecture/overview.md
      - Cloud Infrastructure: architecture/cloud-infrastructure.md
      - Kubernetes: architecture/kubernetes.md
      - Networking: architecture/networking.md
      - Storage: architecture/storage.md
  - User Services:
      - Introduction: user-services/overview.md
      - CKAN:
          - Introduction: user-services/ckan/overview.md
          - Users, Organizations, and Authorization: user-services/ckan/users.md
          - Datasets, Resources, and Groups: user-services/ckan/datasets.md
          - Metadata: user-services/ckan/metadata.md
          - API: user-services/ckan/api.md
          - Extensions: user-services/ckan/extensions.md
      - JupyterHub:
          - Introduction: user-services/jupyterhub/overview.md
          - File System: user-services/jupyterhub/filesystem.md
          - Environments: user-services/jupyterhub/environments.md
          - Alternative Library: user-services/jupyterhub/library.md
          - R: user-services/jupyterhub/r.md
          - Bioconductor: user-services/jupyterhub/bioconductor.md
      - AI/ML API:
          - Introduction: user-services/ai-ml-api/index.md
          - System Architecture: user-services/ai-ml-api/system-architecture.md
          - Data Flow: user-services/ai-ml-api/data-flow.md
          - Security:
              - Authentication and Authorization: user-services/ai-ml-api/security/authentication-and-authorization.md
              - Encryption: user-services/ai-ml-api/security/encryption.md
          - Token Management:
              - CKAN Integration: user-services/ai-ml-api/token-management/ckan-integration.md
              - Token Lifecycle: user-services/ai-ml-api/token-lifecycle.md
          - API Usage:
              - Endpoints: user-services/ai-ml-api/api-usage/endpoints.md
              - Authentication: user-services/ai-ml-api/api-usage/authentication.md
              - Error Handling: user-services/ai-ml-api/api-usage/error-handling.md
          - Scalability: user-services/ai-ml-api/scalability.md
          - Testing: user-services/ai-ml-api/testing.md
  - Administrative Services:
      - Introduction: admin-services/overview.md
      - Keycloak: admin-services/keycloak.md
      - External DNS: admin-services/external-dns.md
      - Cert Manager: admin-services/cert-manager.md
      - Ingress Controller: admin-services/ingress-controller.md
      - Istio: admin-services/istio.md
  - Platform Features:
      - Introduction: features/overview.md
      - Data Sharing: features/data-sharing.md
      - Development Environment: features/development-environment.md
      - Multi-user and Collaboration: features/multi-user-and-collaboration.md
      - Single Sign-On: features/sso.md
      - Elasticity: features/elasticity.md
  - Deployment:
      - Platform Deployment: deployment/platform.md
      - Envoy Filter: deployment/envoy-filter.md
      - AI/ML API: deployment/ai-ml-api.md
  - Repositories: repositories.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ALTERNATIVE-EU
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ALTERNATIVE_EU
  alternate:
    - name: English
      link: /
      lang: en

extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
  - 'javascripts/extra.js'

metadata:
  description: 'Documentation for the ALTERNATIVE Platform'
  keywords: 'ALTERNATIVE, Platform, Documentation, AI, ML, API'
  author: 'ALTERNATIVE-EU'
  robots: 'index, follow'
  generator: 'MkDocs'
  title_suffix: ' - ALTERNATIVE Platform Documentation'

deploy:
  provider: git
  branch: gh-pages
  message: "Deploying to GitHub Pages"
