site_name: ALTERNATIVE Platform Documentation
site_url: https://platform.alternative-project.eu
repo_url: https://github.com/ALTERNATIVE-EU/ai-ml-api
repo_name: ALTERNATIVE-EU/ai-ml-api

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.tabs.link

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Users, Organizations and Authorization: users.md
  - Datasets, Resources and Groups: datasets.md
  - Metadata: metadata.md
  - JupyterHub: jupyter.md
  - AI/ML API:
    - Home: ai-ml-api/index.md
    - Overview:
      - System Architecture: ai-ml-api/overview/system-architecture.md
      - Data Flow: ai-ml-api/overview/data-flow.md
    - Security:
      - Authentication and Authorization: ai-ml-api/security/authentication-and-authorization.md
      - Encryption: ai-ml-api/security/encryption.md
    - Token Management:
      - CKAN Integration: ai-ml-api/token-management/ckan-integration.md
      - Token Lifecycle: ai-ml-api/token-management/token-lifecycle.md
    - API Usage:
      - Endpoints: ai-ml-api/api-usage/endpoints.md
      - Authentication: ai-ml-api/api-usage/authentication.md
      - Error Handling: ai-ml-api/api-usage/error-handling.md
    - Scalability: ai-ml-api/scalability.md
    - Testing: ai-ml-api/testing.md
    - Deployment: ai-ml-api/deployment.md
    - Repositories: ai-ml-api/repositories.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ALTERNATIVE-EU
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ALTERNATIVE_EU

deploy:
  provider: git
  branch: gh-pages
  message: "Deploying to GitHub Pages"
